version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-all:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/prover"
    schedule:
      interval: "weekly"
    groups:
      prover-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    groups:
      dashboard-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
